### your site title here

title: Poly

baseurl: /Poly
sass: 
    style: compressed

exclude:
- README.md
- _site
- CHANGELOG.md
- LICENSE
- deploy-ghpages.sh
- .circleci
- CONTRIBUTING.md
- ISSUE_TEMPLATE.md

include: 
- _pages
- downloads

